tp.admin.test.create_one:
    pattern:    /test/create
    defaults:   { _controller: TestPalAdminBundle:Test:createOne }

tp.admin.test.list:
    pattern:    /test/list
    defaults:   { _controller: TestPalAdminBundle:Test:list }

tp.admin.test.read_one:
    pattern:    /test/{permalink}
    defaults:   { _controller: TestPalAdminBundle:Test:readOne }

tp.admin.test.update_one:
    pattern:    /test/{permalink}/edit
    defaults:   { _controller: TestPalAdminBundle:Test:updateOne }

tp.admin.test.delete_one:
    pattern:    /test/{permalink}/delete
    defaults:   { _controller: TestPalAdminBundle:Test:deleteOne }