testpal_test_routing:
    resource: "@TestPalApiBundle/Resources/config/routing/test.yml"

testpal_question_routing:
    resource: "@TestPalApiBundle/Resources/config/routing/question.yml"

testpal_answer_routing:
    resource: "@TestPalApiBundle/Resources/config/routing/answer.yml"
