testpal.api.test.routing:
    resource: "@TestPalApiBundle/Resources/config/routing/test.yml"

testpal.api.question.routing:
    resource: "@TestPalApiBundle/Resources/config/routing/question.yml"

testpal.api.answer.routing:
    resource: "@TestPalApiBundle/Resources/config/routing/answer.yml"

testpal.api.examination.routing:
    resource: "@TestPalApiBundle/Resources/config/routing/examination.yml"