parameters:
#    test_pal_api.example.class: petrepatrasc\TestPal\ApiBundle\Example

services:
#    test_pal_api.example:
#        class: %test_pal_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
