parameters:
    tp.api.search.service.class: petrepatrasc\TestPal\ApiBundle\Service\SearchService

services:
    tp.api.search.service:
        class: %tp.api.search.service.class%
        arguments: [@doctrine.orm.entity_manager]