parameters:
#    test_pal_api.example.class: petrepatrasc\TestPal\ApiBundle\Example

services:
    testpal_rest_service:
        class: petrepatrasc\TestPal\ApiBundle\Service\RestService
        arguments: [@doctrine.orm.entity_manager]

    testpal_test_service:
        class: petrepatrasc\TestPal\ApiBundle\Service\TestService
        arguments: [@jms_serializer]

    testpal_question_service:
        class: petrepatrasc\TestPal\ApiBundle\Service\QuestionService
        arguments: [@doctrine.orm.entity_manager, @jms_serializer]