parameters:
#    test_pal_admin.example.class: petrepatrasc\TestPal\AdminBundle\Example

services:
    tp.admin.guzzle.service:
        class: petrepatrasc\TestPal\AdminBundle\Service\GuzzleService
        arguments: [@router, @jms_serializer]

    tp.admin.test.service:
        class: petrepatrasc\TestPal\AdminBundle\Service\TestService
        arguments: [@tp.admin.guzzle.service]