tp_test_information:
    pattern:    /test/{permalink}
    defaults:   { _controller: TestPalClientBundle:Test:displayTestInformation }

tp_test_start:
    pattern:    /test/{permalink}/start
    defaults:   { _controller: TestPalClientBundle:Test:startTest }

tp_test_display_questions:
    pattern:    /test/{permalink}/questions/{userKey}
    defaults:   { _controller: TestPalClientBundle:Test:displayQuestions }

tp_test_submit:
    pattern:    /test/{permalink}/submit/{userKey}
    defaults:   { _controller: TestPalClientBundle:Test:submitTest }

tp_test_results:
    pattern:    /test/{permalink}/results/{userKey}
    defaults:   { _controller: TestPalClientBundle:Test:showResults }