testpal_answer_read_all:
    pattern:    /questions/{questionId}/answers
    defaults:   { _controller: TestPalApiBundle:Answer:readAll, _format: json }
    methods:    [GET]

testpal_answer_create_one:
    pattern:    /questions/{questionId}/answers
    defaults:   { _controller: TestPalApiBundle:Answer:createOne, _format: json }
    methods:    [POST]

testpal_answer_read_one:
    pattern:    /answers/{id}
    defaults:   { _controller: TestPalApiBundle:Answer:readOne, _format: json }
    methods:    [GET]

testpal_answer_update_one:
    pattern:    /answers/{id}
    defaults:   { _controller: TestPalApiBundle:Answer:updateOne, _format: json }
    methods:    [PUT]

testpal_answer_delete_one:
    pattern:    /answers/{id}
    defaults:   { _controller: TestPalApiBundle:Answer:deleteOne, _format: json }
    methods:    [DELETE]