testpal_tests_read_all:
    pattern:    /
    defaults:   { _controller: TestPalApiBundle:Test:readAll, _format: json }
    methods:    [GET]

testpal_tests_read_one:
    pattern:    /{permalink}
    defaults:   { _controller: TestPalApiBundle:Test:readOne, _format: json }
    methods:    [GET]

testpal_tests_create_one:
    pattern:    /
    defaults:   { _controller: TestPalApiBundle:Test:createOne, _format: json }
    methods:    [POST]

testpal_tests_update_one:
    pattern:    /{permalink}
    defaults:   { _controller: TestPalApiBundle:Test:updateOne, _format: json }
    methods:    [PUT]

testpal_tests_delete_one:
    pattern:    /{permalink}
    defaults:   { _controller: TestPalApiBundle:Test:deleteOne, _format: json }
    methods:    [DELETE]